#server.port=8080

#spring.application.name=ecom-application
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details= always
#management.endpoint.info.env.enabled=true
#
#management.endpoint.info.app.name=DemoApp
#info.app.version=1.0.0
#
#management.endpoint.shutdown.enabled=true


spring:
 application:
  name:ecom-application
 datasource:
   url: jdbc:postgresql://localhost:5432/pranesh
   username: pranesh
   password: bijinapally
 jpa:
   database: POSTGRESQL
   show-sql: true
   hibernate:
     ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: beans,health
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
server:
  shutdown: graceful

info:
  app:
    name: MyNewApp
    description: App Built By Us
    version: 1.0.0